#!/bin/sh

VENDOR=kyocera
DEVICE=isw12k
OUTDIR=vendor/$VENDOR/$DEVICE
MAKEFILE=../../../$OUTDIR/$DEVICE-vendor-blobs.mk

(cat << EOF) > $MAKEFILE
# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

INTERNAL_RECOVERY_FILES += \\
  $OUTDIR/proprietary/bin/sdgpiocmd:recovery/root/system/bin/sdgpiocmd \\
  $OUTDIR/proprietary/bin/rmt_storage:recovery/root/system/bin/rmt_storage \\
  $OUTDIR/proprietary/lib/libcutils.so:recovery/root/system/lib/libcutils.so \\
  $OUTDIR/proprietary/lib/libstdc++.so:recovery/root/system/lib/libstdc++.so \\
  $OUTDIR/proprietary/lib/liblog.so:recovery/root/system/lib/liblog.so \\
  $OUTDIR/proprietary/lib/libm.so:recovery/root/system/lib/libm.so \\
  $OUTDIR/proprietary/lib/libc.so:recovery/root/system/lib/libc.so \\
  $OUTDIR/proprietary/lib/modules/kc_sdcarddrv.ko:recovery/root/modules/kc_sdcarddrv.ko

EOF

(cat << EOF) > ../../../$OUTDIR/$DEVICE-vendor.mk
\$(call inherit-product, $OUTDIR/$DEVICE-vendor-blobs.mk)
EOF

(cat << EOF) > ../../../$OUTDIR/BoardConfigVendor.mk
EOF
